# Generated by Django 3.0.1 on 2019-12-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additive',
            name='measure',
        ),
        migrations.AddField(
            model_name='additivetype',
            name='measure',
            field=models.CharField(choices=[('DW', 'Dry weight in grams'), ('DV', 'Dry volume in liters'), ('WV', 'Wet volume in liters')], default='DW', max_length=2),
        ),
        migrations.AlterField(
            model_name='additivetype',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='fermentation',
            name='enddate',
            field=models.DateTimeField(blank=True, verbose_name='fermentation end'),
        ),
        migrations.AddConstraint(
            model_name='additive',
            constraint=models.UniqueConstraint(fields=('name', 'brand', 'type'), name='unique_additive_per_brand'),
        ),
        migrations.AddConstraint(
            model_name='fermentable',
            constraint=models.UniqueConstraint(fields=('name', 'brand', 'fermentable_type'), name='unique_fermentable_per_brand'),
        ),
        migrations.AddConstraint(
            model_name='fermentationfermentable',
            constraint=models.UniqueConstraint(fields=('fermentation', 'fermentable'), name='one_fermentable_per_fermentation'),
        ),
        migrations.AddConstraint(
            model_name='yeast',
            constraint=models.UniqueConstraint(fields=('name', 'brand', 'yeastType'), name='unique_yeast_per_brand'),
        ),
    ]
