# Generated by Django 3.0.1 on 2019-12-29 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brews', '0002_auto_20191229_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fermentation',
            name='enddate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fermentation end'),
        ),
    ]
